=== MohamedEldefrawy/XML-Parser/src/main/resources/com/employeexml/employeecrudxml/models/employees.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Employees" type="EmployeesType"/>
    <xs:simpleType name="phoneType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="telephone"/>
            <xs:enumeration value="mobile"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PhoneType">
        <xs:attribute type="phoneType" name="type"/>
    </xs:complexType>
    <xs:complexType name="CountryType">
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="CityType">
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="RegionType">
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="StreetType">
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="BuildingType">
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element type="CountryType" name="Country"/>
            <xs:element type="CityType" name="City"/>
            <xs:element type="RegionType" name="Region"/>
            <xs:element type="StreetType" name="Street"/>
            <xs:element type="BuildingType" name="Building"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AddressesType">
        <xs:sequence>
            <xs:element type="AddressType" name="Address"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PhonesType">
        <xs:sequence>
            <xs:element type="PhoneType" name="Phone"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element type="PhonesType" name="Phones"/>
            <xs:element type="AddressesType" name="Addresses"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id"/>
        <xs:attribute type="xs:string" name="email"/>
        <xs:attribute type="xs:string" name="salary"/>
    </xs:complexType>
    <xs:complexType name="EmployeesType">
        <xs:sequence minOccurs="0">
            <xs:element type="EmployeeType" name="Employee"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MohamedEldefrawy/XML-Parser/src/main/resources/com/employeexml/employeecrudxml/models/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<Employees
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./employees.xsd">
    <Employee name="mohamed" email="mohamed@test.com" salary="12000">
        <Phones>
            <Phone type="mobile" value="01153779995"/>
            <Phone type="telephone" value="035265104"/>
            <Phone type="telephone" value="035265104"/>
        </Phones>
        <Addresses>
            <Address>
                <Country value="EG"/>
                <City value="Alex"/>
                <Region value="ELsyouf"/>
                <Street value="Adeeb"/>
                <Building value="9A"/>
            </Address>
            <Address>
                <Country value="EG"/>
                <City value="Alex"/>
                <Region value="ELsyouf"/>
                <Street value="Adeeb"/>
                <Building value="9A"/>
            </Address>
        </Addresses>
    </Employee>
</Employees>
